 "use client";
import { useEffect,useState } from "react"; import {createClient} from "@/lib/supabase/client"; import type {Product} from "@/lib/types"; import {PageHeader} from "@/components/app-shell";
export default function Inventory(){const [items,setItems]=useState<Product[]>([]);const [name,setName]=useState("");const [price,setPrice]=useState("");const [stock,setStock]=useState("");const [error,setError]=useState("");
 async function load(){const sb=createClient();if(!sb)return;const {data,error}=await sb.from("products").select("*").order("created_at",{ascending:false});if(error)setError(error.message);else setItems((data??[]) as Product[]);}
 useEffect(()=>{load()},[]);
 async function add(e:React.FormEvent){e.preventDefault();const sb=createClient();if(!sb)return;const {error}=await sb.from("products").insert({name,selling_price:Number(price),cost_price:0,stock_quantity:Number(stock),reorder_level:5});if(error)setError(error.message);else{name&&setName("");setPrice("");setStock("");load();}}
 return <><PageHeader title="Inventory" description="Products, stock levels and reorder visibility."/><div className="grid xl:grid-cols-[360px_1fr] gap-5"><form onSubmit={add} className="card p-5"><h2 className="font-black text-lg">Add product</h2><label className="label mt-4">Product name<input className="input" value={name} onChange={e=>setName(e.target.value)} required/></label><label className="label mt-4">Selling price<input className="input" type="number" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label className="label mt-4">Opening stock<input className="input" type="number" value={stock} onChange={e=>setStock(e.target.value)} required/></label><button className="btn btn-primary mt-5 w-full">Save product</button>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}</form>
 <div className="card p-5 overflow-x-auto"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="font-bold">{x.name}</td><td>KES {Number(x.selling_price).toLocaleString()}</td><td>{x.stock_quantity}</td><td>{Number(x.stock_quantity)<=Number(x.reorder_level)?<span className="badge bg-red-50 text-red-700">Reorder</span>:<span className="badge">Healthy</span>}</td></tr>)}</tbody></table></div></div></>;
}
