 "use client";
import {useEffect,useMemo,useState} from "react";import {createClient} from "@/lib/supabase/client";import {PageHeader} from "@/components/app-shell";
export default function POS(){const[products,setProducts]=useState<any[]>([]);const[cart,setCart]=useState<any[]>([]);const[error,setError]=useState("");const[message,setMessage]=useState("");
 async function load(){const sb=createClient();if(!sb)return;const{data,error}=await sb.from("products").select("*").order("name");if(error)setError(error.message);else setProducts(data??[])}useEffect(()=>{load()},[]);
 const total=useMemo(()=>cart.reduce((a,x)=>a+Number(x.selling_price)*x.qty,0),[cart]);
 function add(p:any){setCart(c=>{const x=c.find(i=>i.id===p.id);if(x)return c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i);return[...c,{...p,qty:1}]})}
 async function checkout(){const sb=createClient();if(!sb||!cart.length)return;setError("");setMessage("");const{data,error}=await sb.rpc("record_sale",{p_items:cart.map(x=>({product_id:x.id,quantity:x.qty,unit_price:x.selling_price})),p_payment_method:"cash"});if(error)setError(error.message);else{setMessage(`Sale ${data} recorded successfully.`);setCart([]);load()}}
 return <><PageHeader title="Point of Sale" description="Fast checkout with inventory-aware sales."/><div className="grid lg:grid-cols-[1fr_400px] gap-5"><div className="card p-5"><h2 className="font-black text-lg mb-4">Products</h2><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{products.map(p=><button disabled={Number(p.stock_quantity)<1} onClick={()=>add(p)} key={p.id} className="card p-4 text-left hover:border-emerald-600 disabled:opacity-40"><div className="font-bold">{p.name}</div><div className="text-sm text-[#66756e]">Stock {p.stock_quantity}</div><div className="font-black mt-2">KES {Number(p.selling_price).toLocaleString()}</div></button>)}</div></div><div className="card p-5 h-fit"><h2 className="font-black text-lg">Current sale</h2><div className="mt-4 space-y-3">{cart.map(x=><div className="flex justify-between" key={x.id}><span>{x.name} × {x.qty}</span><b>KES {(x.qty*Number(x.selling_price)).toLocaleString()}</b></div>)}{!cart.length&&<p className="text-[#66756e]">No items added.</p>}</div><div className="border-t mt-5 pt-5 flex justify-between text-xl font-black"><span>Total</span><span>KES {total.toLocaleString()}</span></div><button onClick={checkout} disabled={!cart.length} className="btn btn-primary w-full mt-5 disabled:opacity-40">Complete cash sale</button>{message&&<p className="text-emerald-700 text-sm mt-3">{message}</p>}{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}</div></div></>;
}
